### ISSUE TITLE
Could not pass event EntityChangeBlockEvent to FoliaFlow v2.2 java.lang.IllegalStateException: World mismatch: expected world_the_end but got world

### ISSUE THREAD

**Issue by cgw2023** [Hynse/FoliaFlow#22]
```[21:48:37 ERROR]: Could not pass event EntityChangeBlockEvent to FoliaFlow v2.2
java.lang.IllegalStateException: World mismatch: expected world_the_end but got world
	at net.minecraft.world.level.Level.getCurrentWorldData(Level.java:284) ~[?:?]
	at net.minecraft.world.level.Level.getBlockState(Level.java:901) ~[?:?]
	at org.bukkit.craftbukkit.v1_20_R1.block.CraftBlock.getType(CraftBlock.java:242) ~[kaiiju-1.20.1.jar:git-Kaiiju-"95b2d63"]
	at xyz.hynse.foliaflow.watcher.PortalWatcher.onFallingBlockToBlock(PortalWatcher.java:29) ~[FoliaFlow-2.2.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor283.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[kaiiju-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[kaiiju-api-1.20.1-R0.1-SNAPSHOT.jar:git-Kaiiju-"95b2d63"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[kaiiju-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:61) ~[kaiiju-1.20.1.jar:git-Kaiiju-"95b2d63"]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[kaiiju-1.20.1.jar:git-Kaiiju-"95b2d63"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[kaiiju-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callEntityChangeBlockEvent(CraftEventFactory.java:1383) ~[kaiiju-1.20.1.jar:git-Kaiiju-"95b2d63"]
	at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callEntityChangeBlockEvent(CraftEventFactory.java:1375) ~[kaiiju-1.20.1.jar:git-Kaiiju-"95b2d63"]
	at net.minecraft.world.entity.item.FallingBlockEntity.tick(FallingBlockEntity.java:207) ~[?:?]
	at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1407) ~[?:?]
	at net.minecraft.world.level.Level.guardEntityTick(Level.java:1048) ~[?:?]
	at net.minecraft.server.level.ServerLevel.lambda$tick$12(ServerLevel.java:883) ~[?:?]
	at io.papermc.paper.threadedregions.RegionizedWorldData.forEachTickingEntity(RegionizedWorldData.java:544) ~[kaiiju-1.20.1.jar:git-Kaiiju-"95b2d63"]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:855) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1676) ~[kaiiju-1.20.1.jar:git-Kaiiju-"95b2d63"]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:463) ~[kaiiju-1.20.1.jar:git-Kaiiju-"95b2d63"]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1533) ~[kaiiju-1.20.1.jar:git-Kaiiju-"95b2d63"]
	at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:360) ~[kaiiju-1.20.1.jar:git-Kaiiju-"95b2d63"]
	at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:385) ~[kaiiju-1.20.1.jar:git-Kaiiju-"95b2d63"]
	at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[kaiiju-1.20.1.jar:git-Kaiiju-"95b2d63"]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

```

**Comment by MidnightTale** [comment]
use /ver and send or you can just use [Kaiiju](https://github.com/KaiijuMC/Kaiiju) it have unpatch sand dupe without need this plugin
